services:
  navidrome:
    image: "deluan/navidrome:latest"
    user: "1000:1000"
    environment:
      ND_SCANSCHEDULE: "${ND_SCANSCHEDULE}"
      ND_LOGLEVEL: "${ND_LOGLEVEL}"
      ND_SESSIONTIMEOUT: "${ND_SESSIONTIMEOUT}"
      ND_BASEURL: "${ND_BASEURL}"
    ports:
      - "4533:4533"
    volumes:
      - "jfs-navidrome-config:/data"
      - "jfs-navidrome-data:/music:ro"
    deploy:
      mode: "replicated"
      replicas: 1
      placement:
        constraints:
          - "node.role != manager"

  deemix:
    image: "ghcr.io/bambanah/deemix:latest"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      UMASK_SET: "${UMASK_SET}"
      DEEMIX_SINGLE_USER: "${DEEMIX_SINGLE_USER}"
    ports:
      - "6595:6595"
    volumes:
      - "jfs-deemix-config:/config"
      - "jfs-navidrome-data:/downloads"
    deploy:
      mode: "replicated"
      replicas: 1
      placement:
        constraints:
          - "node.role != manager"

volumes:
  jfs-navidrome-config:
    driver: "juicedata/juicefs"
    driver_opts:
      metaurl: "${JFS_META_URL__NAVIDROME_CONFIG}"
      name: "${JFS_VOLUME_NAME__NAVIDROME_CONFIG}"
      storage: "${JFS_STORAGE}"
      bucket: "${JFS_BUCKET__NAVIDROME_CONFIG}"
      access-key: "${JFS_S3_ACCESS_KEY}"
      secret-key: "${JFS_S3_SECRET_KEY}"
      env:
        AWS_REGION: "${JFS_S3_REGION}"
        MINIO_REGION: "${JFS_S3_REGION}"

  jfs-navidrome-data:
    driver: "juicedata/juicefs"
    driver_opts:
      metaurl: "${JFS_META_URL__NAVIDROME_DATA}"
      name: "${JFS_VOLUME_NAME__NAVIDROME_DATA}"
      storage: "${JFS_STORAGE}"
      bucket: "${JFS_BUCKET__NAVIDROME_DATA}"
      access-key: "${JFS_S3_ACCESS_KEY}"
      secret-key: "${JFS_S3_SECRET_KEY}"
      env:
        AWS_REGION: "${JFS_S3_REGION}"
        MINIO_REGION: "${JFS_S3_REGION}"

  jfs-deemix-config:
    driver: "juicedata/juicefs"
    driver_opts:
      metaurl: "${JFS_META_URL__DEEMIX_CONFIG}"
      name: "${JFS_VOLUME_NAME__DEEMIX_CONFIG}"
      storage: "${JFS_STORAGE}"
      bucket: "${JFS_BUCKET__DEEMIX_CONFIG}"
      access-key: "${JFS_S3_ACCESS_KEY}"
      secret-key: "${JFS_S3_SECRET_KEY}"
      env:
        AWS_REGION: "${JFS_S3_REGION}"
        MINIO_REGION: "${JFS_S3_REGION}"
