services:
  navidrome:
    image: "deluan/navidrome:latest"
    user: "1000:1000"
    environment:
      ND_SCANSCHEDULE: "${ND_SCANSCHEDULE}"
      ND_LOGLEVEL: "${ND_LOGLEVEL}"
      ND_SESSIONTIMEOUT: "${ND_SESSIONTIMEOUT}"
      ND_BASEURL: "${ND_BASEURL}"
    ports:
      - "4533:4533"
    volumes:
      - "omv-navidrome:/data"
      - "omv-music:/music:ro"
    deploy:
      mode: "replicated"
      replicas: 1
      placement:
        constraints:
          - "node.role != manager"

  deemix:
    image: "ghcr.io/bambanah/deemix:latest"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      UMASK_SET: "${UMASK_SET}"
      DEEMIX_SINGLE_USER: "${DEEMIX_SINGLE_USER}"
    ports:
      - "6595:6595"
    volumes:
      - "omv-deemix:/config"
      - "omv-music:/downloads"
    deploy:
      mode: "replicated"
      replicas: 1
      placement:
        constraints:
          - "node.role != manager"

volumes:
  omv-music:
    driver: "local"
    driver_opts:
      type: "nfs"
      o: "addr=omv.xt.local,noatime,nodiratime,nfsvers=4.2"
      device: ":/music"

  omv-navidrome:
    driver: "local"
    driver_opts:
      type: "nfs"
      o: "addr=omv.xt.local,noatime,nodiratime,nfsvers=4.2"
      device: ":/navidrome"

  omv-deemix:
    driver: "local"
    driver_opts:
      type: "nfs"
      o: "addr=omv.xt.local,noatime,nodiratime,nfsvers=4.2"
      device: ":/deemix"
