---
services:
  navidrome:
    image: "deluan/navidrome:latest"
    user: "1000:1000"
    environment:
      ND_SCANSCHEDULE: "${ND_SCANSCHEDULE:-1h}"
      ND_LOGLEVEL: "${ND_LOGLEVEL:-info}"
      ND_SESSIONTIMEOUT: "${ND_SESSIONTIMEOUT:-24h}"
      ND_BASEURL: "${ND_BASEURL}"
    ports:
      - "4533:4533"
    volumes:
      - "/juicefs/services/navidrome/data:/data"
      - "/juicefs/music:/music:ro"
    deploy:
      mode: "replicated"
      replicas: 1
      restart_policy:
        condition: "on-failure"
      placement:
        constraints:
          - "node.role != manager"

  deemix:
    image: "ghcr.io/bambanah/deemix:latest"
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      UMASK_SET: "${UMASK_SET:-022}"
      DEEMIX_SINGLE_USER: "${DEEMIX_SINGLE_USER:-true}"
    ports:
      - "6595:6595"
    volumes:
      - "/juicefs/services/deemix/config:/config"
      - "/juicefs/music:/downloads"
    deploy:
      mode: "replicated"
      replicas: 1
      restart_policy:
        condition: "on-failure"
      placement:
        constraints:
          - "node.role != manager"
